import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ekramul Portfolio",
  description: "Generated by Ekramul",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="px-4 w-full h-[calc(100vh-64px)] overflow-auto hide-scrollbar">
          {children}
        </main>
      </body>
    </html>
  );
}
